import { d6DefaultMeshPreset } from "./d6-default-mesh-preset.mjs";

export const dicePresets = {
  "white-classic-reference": {
    id: "white-classic-reference",
    systemName: "white-classic-constructor",
    displayName: "White Classic Reference",
    dieType: "d6",
    meshPreset: d6DefaultMeshPreset.id,
    sourceTheme: "default",
    author: "Codex Spike",
    version: "1.0.0",
    palette: {
      bodyFill: "#f6f1e7",
      faceFill: "#fffdfa",
      markFill: "#17130f",
      slotOutline: "#d9d0c2",
    },
    faceStyle: {
      kind: "pips",
      contentInset: 24,
      pipScale: 0.142,
      cornerOffset: 0.275,
      midOffset: 0.235,
      centerOffset: 0,
      slotCornerRadius: 14,
      slotOutlineWidth: 0,
    },
    faces: {
      1: { value: 1 },
      2: { value: 2 },
      3: { value: 3 },
      4: { value: 4 },
      5: { value: 5 },
      6: { value: 6 },
    },
  },
  "red-joker-reference": {
    id: "red-joker-reference",
    systemName: "red-joker-constructor",
    displayName: "Red Joker Constructor",
    dieType: "d6",
    meshPreset: d6DefaultMeshPreset.id,
    sourceTheme: "default",
    author: "Codex Spike",
    version: "1.0.0",
    palette: {
      bodyFill: "#b92929",
      faceFill: "#c83333",
      markFill: "#fff7ef",
      slotOutline: "#00000000",
    },
    faceStyle: {
      kind: "pips",
      contentInset: 24,
      pipScale: 0.138,
      cornerOffset: 0.275,
      midOffset: 0.235,
      centerOffset: 0,
      slotCornerRadius: 14,
      slotOutlineWidth: 0,
      labelFontFamily: "Georgia, Times New Roman, serif",
      labelScale: 0.56,
      labelWeight: 700,
    },
    faces: {
      1: { value: 1, kind: "label", text: "J", labelScale: 0.64 },
      2: { value: 2 },
      3: { value: 3 },
      4: { value: 4 },
      5: { value: 5 },
      6: { value: 6 },
    },
  },
  "frog-reference": {
    id: "frog-reference",
    systemName: "frog-constructor",
    displayName: "Frog Die",
    dieType: "d6",
    meshPreset: d6DefaultMeshPreset.id,
    sourceTheme: "default",
    author: "Dice-a-Lot",
    version: "1.0.0",
    palette: {
      bodyFill: "#4a8c3f",
      faceFill: "#5e9f46",
      markFill: "#f6f0de",
      slotOutline: "#00000000",
    },
    faceStyle: {
      kind: "pips",
      contentInset: 24,
      pipScale: 0.142,
      cornerOffset: 0.275,
      midOffset: 0.235,
      centerOffset: 0,
      slotCornerRadius: 14,
      slotOutlineWidth: 0,
      labelFontFamily: "Georgia, Times New Roman, serif",
      labelScale: 0.56,
      labelWeight: 700,
    },
    faces: {
      1: { value: 1, kind: "label", text: "◉", labelScale: 0.72 },
      2: { value: 2 },
      3: { value: 3 },
      4: { value: 4 },
      5: { value: 5 },
      6: { value: 6 },
    },
  },
  "white-fit-probe": {
    id: "white-fit-probe",
    systemName: "white-fit-probe",
    displayName: "White Fit Probe",
    dieType: "d6",
    meshPreset: d6DefaultMeshPreset.id,
    sourceTheme: "default",
    author: "Codex Spike",
    version: "1.0.0",
    palette: {
      bodyFill: "#f6f1e7",
      faceFill: "#fffdfa",
      markFill: "#17130f",
      slotOutline: "#00000000",
    },
    faceStyle: {
      kind: "probe",
      contentInset: 24,
      slotCornerRadius: 14,
      slotOutlineWidth: 0,
      labelScale: 0.2,
      probeStrokeWidth: 6,
      probeDotRadius: 8,
    },
    faces: {
      1: { value: 1, text: "1" },
      2: { value: 2, text: "2" },
      3: { value: 3, text: "3" },
      4: { value: 4, text: "4" },
      5: { value: 5, text: "5" },
      6: { value: 6, text: "6" },
    },
  },
};

export const meshPresets = {
  [d6DefaultMeshPreset.id]: d6DefaultMeshPreset,
};
